# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('un_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('images_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('images_name', models.ImageField(blank=True, upload_to='database/img')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(blank=True, default='')),
                ('product_buy_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_sell_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_quantity', models.PositiveSmallIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Category')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_is_organisation', models.BooleanField(default=False)),
                ('supplier_firstname', models.CharField(max_length=50)),
                ('supplier_lastname', models.CharField(max_length=50)),
                ('supplier_organization_name', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=50, unique=True)),
                ('supplier_phone', models.CharField(max_length=30)),
                ('supplier_address', models.CharField(max_length=50)),
                ('supplier_notes', models.TextField(blank=True, default='')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('suppliers_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Suppliers'),
        ),
    ]
