# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ManyToManyField(related_name='suppliers', to='eshop.Suppliers'),
        ),
    ]
