# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20161119_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.ManyToManyField(related_name='images', to='eshop.Images'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='suppliers_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.Images'),
        ),
    ]
