# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20161122_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.ManyToManyField(related_name='product_photo', to='eshop.Images'),
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='suppliers_photo',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='suppliers_photo',
            field=models.ManyToManyField(related_name='supplier_photo', to='eshop.Images'),
        ),
    ]
