# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:20
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20161122_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='last_update',
        ),
        migrations.AddField(
            model_name='images',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
