# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20161122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='un_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_category_id', to='eshop.Category'),
        ),
    ]
