# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20161122_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_buy_price',
            new_name='buy_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sell_price',
            new_name='sell_price',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_is_organisation',
            new_name='is_organisation',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_organization_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='images',
            name='images_id',
        ),
        migrations.RemoveField(
            model_name='images',
            name='images_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='suppliers_photo',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.ImageField(default='blank_img.gif', editable=False, upload_to='database/img'),
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='eshop.Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='eshop.Suppliers'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='photo',
            field=models.ManyToManyField(related_name='suppliers_photos', to='eshop.Images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='un_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_category', to='eshop.Category'),
        ),
    ]
