# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20161128_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='product_photos', to='eshop.Images'),
        ),
    ]
