# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_auto_20161128_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ('firstname', 'lastname')},
        ),
        migrations.AddField(
            model_name='product',
            name='is_instock',
            field=models.BooleanField(default=True),
        ),
    ]
