# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_auto_20161128_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='eshop.Category'),
        ),
    ]
