# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_auto_20161128_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
