# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_auto_20161128_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Order status'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Paymets', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='shipments',
            options={'verbose_name': 'Shipments', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ('firstname',), 'verbose_name': 'Suppliers', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
