# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eshop', '0018_auto_20161128_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='img/upload'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.TextField(),
        ),
    ]
