# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_auto_20161129_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='content_type',
            new_name='img_content_type',
        ),
    ]
