# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0021_images_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img_content_type',
            new_name='obj_content_type',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_id',
            new_name='obj_id',
        ),
        migrations.RemoveField(
            model_name='images',
            name='products',
        ),
    ]
