# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0023_auto_20161129_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='obj_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='obj_id',
            new_name='object_id',
        ),
    ]
