# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_auto_20161202_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
    ]
