# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0027_image_externalurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_NewProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_OnMainPage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_NewProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_OnMainPage',
            field=models.BooleanField(default=False),
        ),
    ]
