# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0028_auto_20161207_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_instock',
            new_name='is_InStock',
        ),
    ]
