# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0030_auto_20161207_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
