# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0031_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
