# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:49
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0032_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='/Users/pasha.BRE/work/webprojects/static/img/upload'),
        ),
    ]
