# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0032_remove_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='externalURL',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/Users/kakoka/webprojects/static/img/upload'),
        ),
    ]
