# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0033_auto_20161209_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
