# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0034_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/Users/kakoka/work/eshop/static/img/upload'),
        ),
    ]
