# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0038_auto_20161212_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='eshop.Address'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customers',
            name='shipment',
        ),
        migrations.AddField(
            model_name='customers',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipment', to='eshop.Shipments'),
            preserve_default=False,
        ),
    ]
