# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0039_auto_20161212_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Address'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Shipments'),
        ),
    ]
