# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0034_remove_image_externalurl'),
        ('eshop', '0042_remove_image_externalurl'),
    ]

    operations = [
    ]
