# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0034_category_tag'),
        ('eshop', '0043_merge_20161212_2014'),
    ]

    operations = [
    ]
