# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0044_merge_20161212_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/Users/kakoka/webprojects/static/img/upload'),
        ),
    ]
